services:
  postgres:
    container_name: fox-friends-db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fox-friends-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  fox-friends-volume:
    external: true
